### ISSUE TITLE
Version number used in `moo/version.py` was not updated in tagged version `0.6.0`

### ISSUE THREAD

**Issue by dingp** [brettviren/moo#40]
Version number 0.5.7 is used in https://github.com/brettviren/moo/blob/0.6.0/moo/version.py 

This caused warnings like [here](https://github.com/DUNE-DAQ/daq-release/actions/runs/3061577113/jobs/4941518809#step:7:56).

**Comment by brettviren** [comment]
Thanks @dingp !!

I updated `version.py` and tagged 0.6.1.
