### ISSUE TITLE
Some very verbose `print`s in `otypes.py

### ISSUE THREAD

**Issue by philiprodrigues** [brettviren/moo#43]
In the dunedaq use of moo, the print statements at these lines are causing a lot of spew:

https://github.com/brettviren/moo/blob/3a1bce8104158b9d9dddd597db56775382acf1f0/moo/otypes.py#L278

https://github.com/brettviren/moo/blob/3a1bce8104158b9d9dddd597db56775382acf1f0/moo/otypes.py#L489

I guess they weren't meant to make it into a release.

**Comment by plasorak** [comment]
If fixed this here: https://github.com/brettviren/moo/pull/41

**Comment by plasorak** [comment]
@brettviren Could we have another tag without the prints?

**Comment by brettviren** [comment]
Thanks for the mention @plasorak (apparently I'm not getting all github notifications lately) and the report @philiprodrigues.

And thanks for the PR, @plasorak which I saw only after making the same changes manually (and some others).  So, I'll close that, but the effort is appreciated.

Release 0.6.3 has these errant prints removed.

https://github.com/brettviren/moo/releases/tag/0.6.3
